config/routes.rb
Uesku::Application.routes.draw do

 

  resources :places do 
    resources :comments ,:name_prefix=>"place_"
    resources :ratings, :name_prefix=>"place_"
  end

  resources :ratings 
  
  resources :pictures, :only=>[:index,:create,:destroy,:show]

  get "categories/index"
  get "categories/subcategory"

  

  get "profile/show"

  get "main/index"
  get "main/category/:id"  =>"main#category" ,:as=>:main_category
  get "main/location/:id"  =>"main#location", :as=>:main_location

  resources :locations,:only=>[:index] do 
    match 'select', :on=>:collection,:via=>[:get,:post]
    get 'set_city', :on=>:member
  end 

  resources :calendar_events

  resources :my_lessons

  resources :short_messages do
    get 'manage',:on=>:member
    get 'reply', :on=>:member
    post 'new_message',:on=>:collection
    get 'show_messages',:on=>:member
    post 'add_users',:on=>:collection
    post 'remove_users',:on=>:collection
    get 'new_messages',:on=>:member
  end

  resources :friendships  do
    get  'agree',:on=>:member
  end

 

  resources :posts  do
    get 'set_to_top',:on=>:member
    get 'set_to_distillate',:on=>:member
    get 'withdraw_to_top', :on=>:member
    get 'withdraw_distillate',:on=>:member
    resources :comments ,:name_prefix=>"post_"
  end

 resources :groups do
    resources  :posts,:name_prefix=>"group_"
    get "add_member",:on=>:member
    get 'administration',:on=>:member
    get 'approval_member',:on=>:member
    get 'reject_member',:on=>:member
    get 'set_manager',:on=>:member
    get 'withdraw_manager',:on=>:member
 end

  devise_for :admins, :controllers =>{:sessions=>'admin/sessions'}
  get 'admin/companies'=>'admin/companies#index',:as=>:admin_root

  devise_for :users, :controllers => { :omniauth_callbacks=>"users/omniauth_callbacks",:registrations=>"users/registrations" }
  
 

  resources :users,:only=>[:show,:edit] do
    get 'groups',:on=>:member
    get 'messenger',:on=>:member
    get 'profile',:on=>:member
    patch 'update_password',:on=>:collection
  end

  resources :companies ,:except=>[:destroy] do 
    get :select_company, :on=>:collection
    get 'history',:on=>:member
    post 'compare',:on=>:member
    get 'undo',:on=>:member
  end

  resources :lessons, :except=>[:destroy] do
    resources :comments,:name_prefix=>"lesson_"
    resources :scores
    resources :timetables,:name_prefix=>"lesson_"
    get 'undo',:on=>:member
    match 'category',:on=>:member,:via=>[:post,:get]
    match 'district',:on=>:member,:via=>[:post,:get]
    match 'course',:on=>:collection,:via=>[:post,:get]
    get 'history', :on=>:member
    post 'compare',:on=>:member
    get 'company',:on=>:collection
    
  end
  resources :timetables do
    get 'register_user',:on=>:member
    delete 'withdraw_user',:on=>:member
    get 'edit_calendar',:on=>:member
    post 'remove_class_time',:on=>:member
    post 'update_class_time', :on=>:member
    resources :comments,:name_prefix=>"timetable_"
  end

  resources :comments
  resources :replies

  post 'query/group_member_for_management'=>'query#group_member_for_management'
  get 'query/query_companies_auto'
  post 'query/query_companies'
  post 'query/query_users'

  namespace :api,defaults: {format: 'json'} do 
    namespace :v1 do 
      devise_for :users, :skip=>[:omniauth_callbacks]
      resources :calendar_events
      resources :users,:only=>[:show]
      resources :short_messages do
        get 'manage',:on=>:member
        get 'reply', :on=>:member
        post 'new_message',:on=>:collection
        get 'show_messages',:on=>:member
        post 'add_users',:on=>:collection
        post 'remove_users',:on=>:collection
        get 'new_messages',:on=>:member
      end
      resources :friendships  do
        get  'agree',:on=>:member
        post 'query_users',:on=>:collection
      end
    end
  end

  namespace :admin do
    resources :admins
    resources :branches,:except=>[:index,:show,:new]
    resources :lessons  do
      get 'set_audit',:on=>:member
      get 'withdraw_audit',:on=>:member
      get 'list',:on=>:collection
      resources :recommendations
    end
    resources :categories   do
      post 'select', :on=>:collection
      post 'course_select',:on=>:collection
    end
    resources :locations   do
      post 'select', :on=>:collection
      
    end

    resources :companies do
    resources :branches
     get  'set_audit', :on=>:member
     get  'withdraw_audit', :on=>:member
    resources :courses    do
      get  'set_audit', :on=>:member
      get  'withdraw_audit', :on=>:member
    end
    end

  end

  authenticated :user do
    root :to=>'users#show',:as=>:root_user
  end
  authenticated :admin do 
    root :to=>'admin/lessons#index',:as=>:root_admin
  end
  root :to => 'main#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  #attr_accessible :created_time, :owner_id, :lesson_id, :logo, :title,:locked,:description,:lessons
  has_many :group_lessons,:dependent=>:destroy
  has_many :lessons,:through=>:group_lessons
  has_many :posts,:dependent=>:destroy
  has_many :members,:dependent=>:destroy
  belongs_to :owner,:class_name=>'User',:foreign_key=>:owner_id
  has_many :users,:through =>:members
  mount_uploader :logo,AvatarUploader
  validates_presence_of :title,:description
  before_create :add_created_time
  after_create :owner_is_manager
  accepts_nested_attributes_for :group_lessons,:allow_destroy=>true
  #def lessons=(brs)
   # brs.each do  |br|
   #   lesson=Lesson.find(br)
      #self.lessons<<lesson unless self.lessons.index(lesson)
      #end
    #self.lessons.each do |lesson|
     # self.lessons.delete(lesson) unless brs.index(lesson.id.to_s)
    #end
    #end

  def add_member(user)
   if self.locked
     self.members.create(:user_id=>user.id) if self.members.where(:user_id=>user.id).blank?
     false
   else
     self.members.create(:user_id=>user.id,:status=>'approval') if self.members.where(:user_id=>user.id).blank?
     true
   end
  end

  def member?(user_id)
    !(self.members.approval.where(:user_id=>user_id).empty?)
  end

  def manager?(user_id)
    !(self.members.managers.where(:user_id=>user_id).empty?)
  end



    private
    def owner_is_manager
      self.members.create(:user_id=>owner_id,:status=>'approval',:role=>'manager')
    end
    def add_created_time
      self.created_time=Time.now
    end
end

app/controllers/groups_controller.rb
#encoding: UTF-8
class GroupsController < ApplicationController
  before_filter :authenticate_user!,:except=>[:index]
  respond_to :html,:js
  layout :set_layout
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.paginate :page=>params[:page],:per_page=>40

   respond_with @group
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @posts=@group.posts
   respond_with @group do |format|
     format.html do


        if @group.member?(current_user.id)
          render 'show'
        elsif @group.locked?
          render 'about'
        else
          render 'preview'
        end
     end
   end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new

    @group = Group.new
    @group.lessons<<Lesson.find(params[:lesson_id]) unless params[:lesson_id].blank?
    @group.owner_id=current_user.id
    respond_with @group
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    respond_with @group
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.owner_id=current_user.id
     flash[:notice]="班级已创建" if @group.save
    respond_with @group

  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])


      flash[:notice]="班级信息已修改" if @group.update_attributes(group_params)
     respond_with @group
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_with @group
  end

  def add_member
    @group=Group.find(params[:id])
    if @group.add_member(current_user)
    respond_with @group
    else
    redirect_to groups_user_path(current_user.id)
    end

  end

   def administration
     @group=Group.find(params[:id])
     respond_with @group
   end

  def approval_member
     @group=Group.find(params[:id])
     member=Member.find(params[:member])
     member.approval_member
    render :partial=>'pending_members',:layout=>false
  end

  def reject_member
    @group=Group.find(params[:id])
    member=Member.find(params[:member])
    member.destroy
    render :partial=>'pending_members',:layout=>false
  end

  def  set_manager
    @group=Group.find(params[:id])
    member=Member.find(params[:member])
    member.set_as_manager
    render :partial=>'managers',:layout=>false
  end

  def withdraw_manager
    @group=Group.find(params[:id])
    member=Member.find(params[:member])
    member.withdraw_manager
    render :partial=>'managers',:layout=>false
  end
  
  private
  def group_params
    params.required(:group).permit(:created_time, :owner_id, :lesson_id, :logo, :title,:locked,:description,:group_lessons_attributes=>[:_destroy,:id,:lesson_id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= nested_form_for(@group,:html=>{:multipart=>true}) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title,"名称" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :logo,'标志' %>
    <%= f.file_field :logo %>
  </div>
  <div class='field'>
    <%=f.label :locked, '私有' %>
    <%=f.select :locked, [['否',false],['是',true]]%>
  </div>
  <div class='field'>
    <%=f.label :description,'简介'%>
    <%=f.text_area :description %>
  </div>
  <div class="actions">
      <%= f.submit '提交' %>
  </div>
  <div class="field">

    <%= f.hidden_field :owner_id %>
     相关课程： <br/>
    <%=f.fields_for :group_lessons do |lesson| %>
      <%=lesson.hidden_field :lesson_id%>
      <% unless lesson.object.lesson_id.blank? %>
        <%=lesson.object.lesson.title%>
        <%=lesson.object.lesson.branch.name%>
      <% else %>
        <%=text_field_tag :lesson_name ,nil,:class=>'lesson_name_field'%>
      <% end %>
        <%=lesson.link_to_remove '删除'%>
      
    <% end %>
    
    </div>

<% end %>

app/views/groups/_head.html.erb
<div id='head'>

  <%= image_tag group.logo.to_s,:width=>100,:height=>100,:class=>'float_left logo' %>
  <div id="group_title" class='float_left'> <%=link_to  group.title, group_path(group) %></div>

</div>

app/views/groups/_managers.html.erb

<% @group.members.managers.each do |manager| %>
  <ul class="lists">
    <li> <%=manager.name %></li>
    <li> <%=link_to '降为普通成员',withdraw_manager_group_path(@group,:member=>manager),:remote=>true %></li>
  </ul>
<% end %>

app/views/groups/_pending_members.html.erb
<%="没有待审核的用户" if @group.members.pending.empty? %>
<% @group.members.pending.each do |member|%>
    <ul class="lists">
      <li><%=member.user.name %></li>
      <li><%=member.user.email %></li>
      <li><%=link_to '批准',approval_member_group_path(@group,:member=>member),:remote=>true %>
      <%=link_to '拒绝',reject_member_group_path(@group,:member=>member),:remote=>true %></li>
    </ul>
<% end %>

app/views/groups/about.html.erb
<p id="notice"><%= notice %></p>
<div id="wrap">
  <div>
    <p>
      <%=render :partial=>'head',:locals=>{:group=>@group}%>

    <div id='group_info'>
      <b>管理者:</b>   <br/>
      <% @group.members.managers.each do |manager| %>
          <%=manager.name %>    <br/>
      <% end %>
      <b>创建时间:</b>
      <%= @group.created_time.to_s(:db) %>    <br/>
      <b>相关课程:</b>
      <% @group.lessons.each do |lesson|%>
       <%=lesson.title %></div>  <br/>
       <% end %>
    </p>
  </div>

      <div id='description'><%=@group.description %><%=button_to '加入',add_member_group_path(@group) %></div>


</div>


app/views/groups/administration.html.erb




<%=render :partial=>'head',:locals=>{:group=>@group}%>
<div class="float_right">
  <div id="tools_menu">
      <h1>课吧信息</h1>
      <%=render 'group_info'%>
  </div>
 <%=link_to '修改课吧信息',edit_group_path(@group)%>
</div>
<div id="main_content">
  <div class='detail_bar'><div class="detail_head">描述：</div> </div>
  <div class="details">
    <div id='description'><%=@group.description %> </div>
  </div>
  <div class='detail_bar'><div class='detail_head'>管理者列表</div></div>
  <div id='details'>
    <div id='manager_list'><%=render 'managers'%></div>
    <div id="query_member" class="form_list">
        <b>添加管理员</b> <br/>
        <%=form_tag query_group_member_for_management_path,:remote=>true,:id=>'query_name' do %>
          <%= label_tag '用户名称'%>
          <%= text_field_tag :user_name %>
          <%=hidden_field_tag :group_id,@group.id %>
          <%=submit_tag '搜索' %>
        <% end %>
        <div id="query_result"></div>
    </div>
  </div>
  <div class='detail_bar'><div class='detail_head'>审请加入用户列表</div></div>
  <div id="details">
    <div class="form_list"><%=render 'pending_members'%> </div>
  </div>
</div>

app/views/groups/edit.html+phone.erb
<%=content_tag :div, id:mobile_page_id, data: {role: 'page',dialog: true} do %>
  <%=content_tag :div, data:{role: 'header'} do %>
    <h2>修改课吧</h2>
  <% end %>
  <%=content_tag :div ,data: {role: 'content'} do %>
    <%=render 'form'%>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<h1>修改信息</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html+phone.erb
<%=content_tag :div, id: mobile_page_id, data: {role: 'page'} do %>	
  <%=render 'shares/header'%>
  <%=content_tag :div, data: {role: 'content'} do %>
		<ul data-role='listview',data-inset='true' class='lists_phone'>
      <li data-role='list-divider'>课吧列表</li>
		  <%=render 'list_group'%>
		</ul>
	

	<div id="paginate_area">
		<%=will_paginate @groups,:prev_label=>'上一页',:next_label=>'下一页'%>
	</div>
   <%=render 'shares/footer'%>
  <% end%>
 
<% end %>

app/views/groups/index.js.erb
$("ul[data-role='listview'].lists_phone").append('<%=j render 'list_group' %>').listview('refresh');
<% if @groups.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @groups %>');
<% else %>
	$(document).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/groups/new.html.erb
<h1>创建课吧</h1>

<%= render 'form' %>

<%= link_to '返回',:back %>

app/views/groups/preview.html+phone.erb
<%=content_tag :div,id: mobile_page_id, data: {role: 'page'} do %>
  <%=render 'shares/header'%>
  <%=content_tag :div,data:{role: 'content'} do %>
    <%=render :partial=>'head',:locals=>{:group=>@group}%>
    <div id='group_info'>
      <%=render 'group_info'%>
      <b>管理者:</b>  
      <% @group.members.managers.each do |manager| %>
        <div>  <%=manager.name %> </div>  
      <% end %>
    </div>
    <div id='description'>
      <%=@group.description %>
      <%=button_to '加入',add_member_group_path(@group) %>
    </div>
    <%=content_tag :div,id: 'posts_list',data:{:"group-id"=>@group.id} do %><% end %>
    <%=render 'shares/footer'%>
  <% end %>
<% end %>

app/views/groups/show.html+phone.erb
<%=content_tag :div, id: mobile_page_id, data:{role: 'page'} do %>
  <%=render 'shares/header'%>
  <%=content_tag :div, data:{role: 'content'} do %>
    <%=render :partial=>'head',:locals=>{:group=>@group}%>
    <div data-role='collapsible' >
      <h3>课吧信息</h3>
      <div id='group_info'>
       <%=render 'group_info'%>
        <ul>
          <li><b>管理者:</b> </li>
          <li><ul>
              <% @group.members.managers.each do |manager| %>
                   <li> <div>   <%=manager.name %>  </div></li>
              <% end %>
          </ul></li>
        </ul>
      </div>
      <%= link_to '管理', administration_group_path(@group) if @group.owner==current_user%>
    </div>
    <div class="phone_bar">
      <h3>最新话题</h3>
      <%=link_to '写帖子',new_post_path(:group_id=>@group.id),data:{role:'button',inline:true,icon: 'edit',ajax: false }%>
    </div>
    <%=content_tag :div,id: "posts_list", data:{group_id: @group.id} do %><% end %>
    <%=render 'shares/footer'%>
  <% end %> 
<% end %>

app/views/groups/show.html.erb
  <%=render :partial=>'head',:locals=>{:group=>@group}%>
  <div class='float_right'>
    <div id='tools_menu' >
        <h1>课吧信息</h1>

        <div id='group_info'>
         <%=render 'group_info'%>
          <ul>
            <li><b>管理者:</b> </li>
            <li><ul>
                <% @group.members.managers.each do |manager| %>
                     <li> <div>   <%=manager.name %>  </div></li>
                <% end %>
            </ul></li>
          </ul>
        </div>

    </div>
    <%= link_to '管理', administration_group_path(@group) if @group.owner==current_user%>
   </div>
    <div id='main_content'>
      <div class="detail_bar"><div class='detail_head'>最新话题</div></div>

    <div id="dylist" class='details'>
        <div id="post_list" data-group-id=<%=@group.id %>></div>

    </div>
    <div id="comment">
      <fieldst>
       
        <%=form_for [@group,Post.new], :remote=>true do |f| %>
            <p>  
              <%=f.label :title,"标题:"%><%=f.text_field :title,:size=>70 %>
            </p>  
            <div class="comment_area"><%=f.kindeditor :content %></div>
              <%=f.submit '发布' %>
            <div id="errmsgs"></div>
        <% end %>
      </fieldst>
    </div>
    </div>