config/routes.rb
Uesku::Application.routes.draw do

 

  resources :places do 
    resources :comments ,:name_prefix=>"place_"
    resources :ratings, :name_prefix=>"place_"
  end

  resources :ratings 
  
  resources :pictures, :only=>[:index,:create,:destroy,:show]

  get "categories/index"
  get "categories/subcategory"

  

  get "profile/show"

  get "main/index"
  get "main/category/:id"  =>"main#category" ,:as=>:main_category
  get "main/location/:id"  =>"main#location", :as=>:main_location

  resources :locations,:only=>[:index] do 
    match 'select', :on=>:collection,:via=>[:get,:post]
    get 'set_city', :on=>:member
  end 

  resources :calendar_events

  resources :my_lessons

  resources :short_messages do
    get 'manage',:on=>:member
    get 'reply', :on=>:member
    post 'new_message',:on=>:collection
    get 'show_messages',:on=>:member
    post 'add_users',:on=>:collection
    post 'remove_users',:on=>:collection
    get 'new_messages',:on=>:member
  end

  resources :friendships  do
    get  'agree',:on=>:member
  end

 

  resources :posts  do
    get 'set_to_top',:on=>:member
    get 'set_to_distillate',:on=>:member
    get 'withdraw_to_top', :on=>:member
    get 'withdraw_distillate',:on=>:member
    resources :comments ,:name_prefix=>"post_"
  end

 resources :groups do
    resources  :posts,:name_prefix=>"group_"
    get "add_member",:on=>:member
    get 'administration',:on=>:member
    get 'approval_member',:on=>:member
    get 'reject_member',:on=>:member
    get 'set_manager',:on=>:member
    get 'withdraw_manager',:on=>:member
 end

  devise_for :admins, :controllers =>{:sessions=>'admin/sessions'}
  get 'admin/companies'=>'admin/companies#index',:as=>:admin_root

  devise_for :users, :controllers => { :omniauth_callbacks=>"users/omniauth_callbacks",:registrations=>"users/registrations" }
  
 

  resources :users,:only=>[:show,:edit] do
    get 'groups',:on=>:member
    get 'messenger',:on=>:member
    get 'profile',:on=>:member
    patch 'update_password',:on=>:collection
  end

  resources :companies ,:except=>[:destroy] do 
    get :select_company, :on=>:collection
    get 'history',:on=>:member
    post 'compare',:on=>:member
    get 'undo',:on=>:member
  end

  resources :lessons, :except=>[:destroy] do
    resources :comments,:name_prefix=>"lesson_"
    resources :scores
    resources :timetables,:name_prefix=>"lesson_"
    get 'undo',:on=>:member
    match 'category',:on=>:member,:via=>[:post,:get]
    match 'district',:on=>:member,:via=>[:post,:get]
    match 'course',:on=>:collection,:via=>[:post,:get]
    get 'history', :on=>:member
    post 'compare',:on=>:member
    get 'company',:on=>:collection
    
  end
  resources :timetables do
    get 'register_user',:on=>:member
    delete 'withdraw_user',:on=>:member
    get 'edit_calendar',:on=>:member
    post 'remove_class_time',:on=>:member
    post 'update_class_time', :on=>:member
    resources :comments,:name_prefix=>"timetable_"
  end

  resources :comments
  resources :replies

  post 'query/group_member_for_management'=>'query#group_member_for_management'
  get 'query/query_companies_auto'
  post 'query/query_companies'
  post 'query/query_users'

  namespace :api,defaults: {format: 'json'} do 
    namespace :v1 do 
      devise_for :users, :skip=>[:omniauth_callbacks]
      resources :calendar_events
      resources :users,:only=>[:show]
      resources :short_messages do
        get 'manage',:on=>:member
        get 'reply', :on=>:member
        post 'new_message',:on=>:collection
        get 'show_messages',:on=>:member
        post 'add_users',:on=>:collection
        post 'remove_users',:on=>:collection
        get 'new_messages',:on=>:member
      end
      resources :friendships  do
        get  'agree',:on=>:member
        post 'query_users',:on=>:collection
      end
    end
  end

  namespace :admin do
    resources :admins
    resources :branches,:except=>[:index,:show,:new]
    resources :lessons  do
      get 'set_audit',:on=>:member
      get 'withdraw_audit',:on=>:member
      get 'list',:on=>:collection
      resources :recommendations
    end
    resources :categories   do
      post 'select', :on=>:collection
      post 'course_select',:on=>:collection
    end
    resources :locations   do
      post 'select', :on=>:collection
      
    end

    resources :companies do
    resources :branches
     get  'set_audit', :on=>:member
     get  'withdraw_audit', :on=>:member
    resources :courses    do
      get  'set_audit', :on=>:member
      get  'withdraw_audit', :on=>:member
    end
    end

  end

  authenticated :user do
    root :to=>'users#show',:as=>:root_user
  end
  authenticated :admin do 
    root :to=>'admin/lessons#index',:as=>:root_admin
  end
  root :to => 'main#index'

end

app/views/admin/admins/_form.html.erb
<%=form_for [:admin,@user] do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%=f.label :name, '姓名'%>    <br/>
    <%=f.text_field :name %>      <br/>
  <%=f.label :email, '邮箱'%>     <br/>
  <%=f.text_field :email %>      <br/>
   <%=f.label :password,"密码"%>      <br/>
    <%=f.password_field :password %>      <br/>
    <%=f.label :password_confirmation,"确认密码"  %>  <br/>
    <%=f.password_field :password_confirmation %> <br>
    <%=f.fields_for :roles do |r|%>
    <% Admin::ROLES.each do |key,role|%>
        <%=check_box_tag 'admin[roles][]',key,@user.roles.include?(role) %>  <%=role %>
            <% end %>
     <% end %>
    <br/>
    <%=f.submit '提交'%>

<% end %>

app/views/admin/admins/edit.html.erb
<h1>修改用户信息</h1>
<%=render 'form' %>
<%=link_to '显示',admin_admin_path(@user) %>
<%=link_to '返回',:back %>

app/views/admin/admins/index.html.erb
<h1>用户管理</h1>
<table>
  <tr>
    <th>email</th>
    <th>姓名</th>
    <th>权限</th>
    <th>状态</th>
    <th></th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td> <%=user.email %></td>
    <td> <%=user.name %></td>
    <td> <% user.roles.each do |role| %>
          <%=role %> <% end %></td>
    <td><%=user.in_active? ? '正常': '已删除'%></td>
    <td> <%=link_to '显示',admin_admin_path(user)%></td>
    <td><%=link_to '修改',edit_admin_admin_path(user)%></td>
    <td><%=link_to '删除',[:admin,user], method: :delete, data: {confirm: '你确定删除该用户吗？'}%></td>
  </tr>
      <% end %>
</table>
<%=link_to '新建用户',new_admin_admin_path %>

app/views/admin/admins/new.html.erb
<h1>新建用户</h1>
<%=render 'form' %>
<%=link_to '返回',:back %>

app/views/admin/admins/show.html.erb
<h1>用户信息</h1>
姓名：<%=@user.name %><br/>
email:<%=@user.email %> <br/>
角色：<br/>
<% @user.roles.each do |role| %>
    <%=role %>
<% end %>


<%=link_to '修改',edit_admin_admin_path(@user) %>
<%=link_to '返回',admin_admins_path %>