config/routes.rb
Uesku::Application.routes.draw do

 

  resources :places do 
    resources :comments ,:name_prefix=>"place_"
    resources :ratings, :name_prefix=>"place_"
  end

  resources :ratings 
  
  resources :pictures, :only=>[:index,:create,:destroy,:show]

  get "categories/index"
  get "categories/subcategory"

  

  get "profile/show"

  get "main/index"
  get "main/category/:id"  =>"main#category" ,:as=>:main_category
  get "main/location/:id"  =>"main#location", :as=>:main_location

  resources :locations,:only=>[:index] do 
    match 'select', :on=>:collection,:via=>[:get,:post]
    get 'set_city', :on=>:member
  end 

  resources :calendar_events

  resources :my_lessons

  resources :short_messages do
    get 'manage',:on=>:member
    get 'reply', :on=>:member
    post 'new_message',:on=>:collection
    get 'show_messages',:on=>:member
    post 'add_users',:on=>:collection
    post 'remove_users',:on=>:collection
    get 'new_messages',:on=>:member
  end

  resources :friendships  do
    get  'agree',:on=>:member
  end

 

  resources :posts  do
    get 'set_to_top',:on=>:member
    get 'set_to_distillate',:on=>:member
    get 'withdraw_to_top', :on=>:member
    get 'withdraw_distillate',:on=>:member
    resources :comments ,:name_prefix=>"post_"
  end

 resources :groups do
    resources  :posts,:name_prefix=>"group_"
    get "add_member",:on=>:member
    get 'administration',:on=>:member
    get 'approval_member',:on=>:member
    get 'reject_member',:on=>:member
    get 'set_manager',:on=>:member
    get 'withdraw_manager',:on=>:member
 end

  devise_for :admins, :controllers =>{:sessions=>'admin/sessions'}
  get 'admin/companies'=>'admin/companies#index',:as=>:admin_root

  devise_for :users, :controllers => { :omniauth_callbacks=>"users/omniauth_callbacks",:registrations=>"users/registrations" }
  
 

  resources :users,:only=>[:show,:edit] do
    get 'groups',:on=>:member
    get 'messenger',:on=>:member
    get 'profile',:on=>:member
    patch 'update_password',:on=>:collection
  end

  resources :companies ,:except=>[:destroy] do 
    get :select_company, :on=>:collection
    get 'history',:on=>:member
    post 'compare',:on=>:member
    get 'undo',:on=>:member
  end

  resources :lessons, :except=>[:destroy] do
    resources :comments,:name_prefix=>"lesson_"
    resources :scores
    resources :timetables,:name_prefix=>"lesson_"
    get 'undo',:on=>:member
    match 'category',:on=>:member,:via=>[:post,:get]
    match 'district',:on=>:member,:via=>[:post,:get]
    match 'course',:on=>:collection,:via=>[:post,:get]
    get 'history', :on=>:member
    post 'compare',:on=>:member
    get 'company',:on=>:collection
    
  end
  resources :timetables do
    get 'register_user',:on=>:member
    delete 'withdraw_user',:on=>:member
    get 'edit_calendar',:on=>:member
    post 'remove_class_time',:on=>:member
    post 'update_class_time', :on=>:member
    resources :comments,:name_prefix=>"timetable_"
  end

  resources :comments
  resources :replies

  post 'query/group_member_for_management'=>'query#group_member_for_management'
  get 'query/query_companies_auto'
  post 'query/query_companies'
  post 'query/query_users'

  namespace :api,defaults: {format: 'json'} do 
    namespace :v1 do 
      devise_for :users, :skip=>[:omniauth_callbacks]
      resources :calendar_events
      resources :users,:only=>[:show]
      resources :short_messages do
        get 'manage',:on=>:member
        get 'reply', :on=>:member
        post 'new_message',:on=>:collection
        get 'show_messages',:on=>:member
        post 'add_users',:on=>:collection
        post 'remove_users',:on=>:collection
        get 'new_messages',:on=>:member
      end
      resources :friendships  do
        get  'agree',:on=>:member
        post 'query_users',:on=>:collection
      end
    end
  end

  namespace :admin do
    resources :admins
    resources :branches,:except=>[:index,:show,:new]
    resources :lessons  do
      get 'set_audit',:on=>:member
      get 'withdraw_audit',:on=>:member
      get 'list',:on=>:collection
      resources :recommendations
    end
    resources :categories   do
      post 'select', :on=>:collection
      post 'course_select',:on=>:collection
    end
    resources :locations   do
      post 'select', :on=>:collection
      
    end

    resources :companies do
    resources :branches
     get  'set_audit', :on=>:member
     get  'withdraw_audit', :on=>:member
    resources :courses    do
      get  'set_audit', :on=>:member
      get  'withdraw_audit', :on=>:member
    end
    end

  end

  authenticated :user do
    root :to=>'users#show',:as=>:root_user
  end
  authenticated :admin do 
    root :to=>'admin/lessons#index',:as=>:root_admin
  end
  root :to => 'main#index'

end

app/models/company.rb
class Company < ActiveRecord::Base

  #attr_accessible :description,  :name, :tags, :website,:branches_attributes
   has_many :branches,:dependent=>:destroy
   has_many :courses,:dependent=>:destroy
   has_many :lessons, :through=>:courses
   has_paper_trail
   accepts_nested_attributes_for :branches
   before_save :moniter_clients
   after_create :renew_score
   after_update :renew_update_score
  include AuditContent
   scope :published, ->{where(:audit => true)}
   validates_uniqueness_of :name

   

   def versioned_branches
     real_branches=[]

    if self.version.nil?
      real_branches=self.branches
    else
      created_time=self.version.previous.created_at
      #previous_created_time=self.version.previous.try(:created_at)
      p created_time
      self.branches.each do |br|
        branch_version=br.versions.where("created_at < ?",created_time).last
        p "version=#{branch_version}"
        unless branch_version.nil?
           branch= branch_version.next.nil? ? br : branch_version.next.reify
        
        real_branches<<branch 
        end
      end
    end
     real_branches
   end

   def get_version(arg)
   self.versions.find(arg).next.nil? ? self : self.versions.find(arg).next.reify
   end

   private
   def moniter_clients
    self.updated_at=Time.now if self.changed_for_autosave?
   end

   def renew_score
      User.find(self.originator).update_attributes(:score=>User.find(self.originator).score+10)
  end

  def renew_update_score
      User.find(self.originator).update_attributes(:score=>User.find(self.originator).score+5) 
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminBaseController
  # GET /companies
  # GET /companies.json
  def index
    
    @companies=Company.paginate(:page=>params[:page],:per_page=>40)
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # _show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    @company.branches.build(:geolng=>116.31051333,:geolat=>39.95548177)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to [:admin, @company], notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to admin_companies_url }
      format.json { head :no_content }
    end
  end
  
  private
  def company_params
    params.required(:company).permit(:description,  :name, :tags, :website,:branches_attributes=>[:destroy,:id,:city_id, :district_id, :geolat, :geolng, :name, :phone, :province_id,:street, :website,:company_id,:company_attributes])
  end

 
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!, :except=>[:index,:show]
	respond_to :html
  layout :set_layout
  def index
    @companies=Company.paginate :page=>params[:page],:per_page=>40
    respond_with @companies do |format|
      format.html
      format.js
    end
  end

  def show
    @company=Company.find(params[:id])
    respond_with @company
  end

  def new
  	@company=Company.new
  	@company.branches.build(:geolng=>116.31051333,:geolat=>39.95548177)
  	respond_with @company

  end

  def edit
  	@company=Company.find(params[:id])
  	respond_with @company
  end

  def create
  	@company=Company.new(company_params)
  	@company.save
  	respond_with @company
  end

  def update
  	@company=Company.find(params[:id])
  	@company.update_attributes(company_params)
  	respond_with @company
  end

  def select_company
  	@companies=Company.order('id DESC').paginate :page=>params[:page],:per_page=>40
    respond_with @companies do |format|
    	format.html {render :partial=>'companies_partial',:layout=>false}
    end
  end


  def history
    @company=Company.find(params[:id])
    @history=@company.versions
    respond_with [@company,@history]
  end


  def compare
    company=Company.find(params[:id])
    @current=company.get_version(params[:versions][0])
    @previous=company.get_version(params[:versions][1])
    respond_with [@current,@previous]
  end

  def undo
    company_object=Company.find(params[:id])
    @company=params[:version_id].nil? ? company_object : company_object.versions.find(params[:version_id]).reify
    render 'edit'
  end
  
  private
  
  def company_params
    params.required(:company).permit(:description,  :name, :tags, :website,branches_attributes:[:_destroy,:id,:city_id, :district_id, :geolat, :geolng, :name, :phone, :province_id,:street, :website,:company_id])
  end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
  def add_new_branch(name)
      link_to_function name,nil  do |page|
        page.insert_html :bottom, :branches, :partial => 'branch', :object => Branch.new
      end

  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_branch_fields.html.erb


 
<div class="branch">
  <fieldset>
  <div class="float_left">
        <%=f.hidden_field :id %>
        <%=f.link_to_remove '删除' %>
        <div class="field">
          <%=f.label :name,"分支名称"%><br/>
          <%=f.text_field :name %> 
        </div>
        <div class='field'>
          <%=f.label :phone,"电话"%> <br/>
          <%=f.text_field :phone %>
        </div>
        <div class='field'>
          <%=f.label :website, "分支网址"%><br/>
          <%=f.text_field :website %>
        </div>
        <div class='address'>
          地址：<%=f.select :province_id,options_for_select(Location.roots.order(:id).collect {|p| [p.name,p.id]}),{},:class=>'province' %> 
          <%=f.select :city_id,options_for_select(Location.first_cities.collect{|p| [p.name,p.id]}),{},:class=>'city'  %> 
          <%=f.collection_select :district_id,Location.first_districts,:id,:name,{},:class=>'district' %> <br/> 
          <%=f.text_field :street,:class=>'street' %><div class='map_notice'></div>
        </div>
        <div class='field undisplay'>
          地理坐标：<br/>
          经度：<%=f.text_field :geolng,:class=>'positionx' %>  <br/>
          纬度:<%=f.text_field :geolat,:class=>'positiony' %>
        </div>
      </div>
      <div class="float_right">

        <div><b>点击地图设定分支所在位置：</b></div>
        <%=tag "div",{:class=>"mymap set_point",:id=>"mymap#{rand(1000)}"},true%>
        <%=tag "/div",nil,true%>
      </div>
     
     
    </fieldset>
</div>
  
 

app/views/companies/_companies_partial.html.erb
<div>
	<%=render 'select_company' %>
<div id='page_area'><%=will_paginate @companies,:action=>'select_company',:previous_label=>'上一页',:next_label=>'下一页'%></div>
</div>

app/views/companies/_form.html.erb
<%= nested_form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name,'名称' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website,"网址" %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :tags,"标签" %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :description,"教育机构简介" %><br />
    <%= f.kindeditor :description %>
  </div>
  <div id='branches'>
    <%=f.fields_for :branches,@company.versioned_branches %>
  </div>

  <%=f.link_to_add "新增分支",:branches%>
  <div class="actions">
    <%= f.submit "提交" %>
  </div>

<% end %>

app/views/companies/_list_name.html.erb
 <% @companies.each do |company| %>
 <li><%=link_to company.name, company_path(company) %></li>
 <% end%>

app/views/companies/_query_select_company.html.erb
<div>
	<% if @companies.blank? %>
	<p>没有你查找的机构， 请<%=link_to '点击',new_company_path %>新建你查找的机构</p>
	<% end %>
	<%=render '/companies/select_company'%>
</div>

app/views/companies/_select_company.html.erb
<div>
<%=form_tag '/lessons/course' do %>
	<% @companies.each do |company| %>
	<div>
		<%=radio_button_tag 'company_id',company.id %>
		<%=link_to company.name,company_path(company),:target=>'_blank'%><br/>
	分支：<br/>
	<ul>
	<% company.branches.each do |branch| %>
		<li><%=branch.name %></li>
	<% end %>
    </ul>
	</div>
	<% end %>
	<%=submit_tag '下一步' %>

<% end %>
</div>

app/views/companies/_show_partial.html.erb
<div class='subtitle'>
  <p><b><%=company.version.nil? ? company.versions.last.created_at.localtime : company.version.previous.created_at.localtime %>的版本</b></p>
  <p>
    <% unless company.originator.nil? %>
                    <%=link_to whodoit(company.originator).try(:name),profile_user_path(whodoit(company.originator)) %>
                    <%=link_to '讨论','#',:remote=>true,:data=>{:users=>[company.originator]}%>
                    <%=link_to '修改', undo_company_path(company,:version_id=>company.version.try(:id)) %>
                <% end %>
  </p>
</div>
<p>
  <b>名称:</b>
  <%= company.name %>
</p>

<p>
  <b>网址:</b>
  <%= company.website %>
</p>

<p>
  <b>标签:</b>
  <%= company.tags %>
</p>

<p>
  <b>公司简介:</b>
  <%= raw(company.description) %>
</p>

  
<div>
  <b>地点</b> <br/>

  <% n=rand(10000) %>
  <%company.versioned_branches.each do |branch| %>

      <fieldset>
        
          <div class='branch_message'>
            <p><b>名称</b><%=branch.name%></p>
            <p><b>电话</b><%=branch.phone%></p>
            <p><b>地址</b><%=branch.address %></p>
            <p><b>分支网址</b><%=branch.website%></p>
             <div>
                <% branch.lessons.each do |lesson|%>
                  <div>   课程名称：<%=lesson.title %> 
                          总分：<%=lesson.rank %> 
                          <%=link_to '详细',lesson_path(lesson)%>
                  </div>

                <% end %>
             </div>
          </div>
           <%= tag "div",{:id=>"mymap#{n}", :class=>"course_map small_map",:data=>{:positionx=>branch.geolng,:positiony=>branch.geolat}},true  %>  <%=tag "/div","",true %>
        
         

        </fieldset>
      <% n+=1 %>
  <% end %>
  </div>

app/views/companies/index.html+phone.erb
<%=content_tag :div, id: mobile_page_id, data: {role: 'page'} do%>
  <%=render 'shares/header'%>
  <%=content_tag :div,data: {role: 'content'} do %>
  

   <ul data-role="listview" class='lists_phone'>
     <%=render "list_name"%>
   </ul>  
  
  
  <div id="will_paginate">
	  <%=will_paginate @companies%>
  </div>
   <%=render 'shares/footer'%>
  <% end %>
 
 
<% end %>

app/views/companies/index.html.erb
<div class='columns_list'>

 <ul class='columns' data-columns='2'>
   <%=render "list_name"%>
 </ul>  
</div>
<div>
	<%=link_to '新建教育机构',new_company_path %>
</div>
<div><%=will_paginate @companies,:prev_label=>'上一页',:next_label=>'下一页'%></div>

app/views/companies/index.js.erb
$("ul[data-role='listview'].lists_phone").append('<%=j render 'list_name' %>').listview('refresh');
<% if @companies.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @companies %>');
<% else %>
	$(document).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/companies/new.html.erb
<h1>新建教育机构</h1>

<%= render 'form' %>

<%= link_to '返回', :back %>

app/views/companies/new_lessons.html.erb
<%= form_for @company do |com| %>
    <%=com.fields_for :course do |f| %>
        <%= f.label :title,"课程名称" %>  <br/>
        <%= f.text_field :title %>   <br/>
        <%= f.label :category_id,"类别" %> <br/>
        <% @course.category=Category.roots.first if @course.category.nil?%>
        <div id="course_category"> <%= render :partial=>"/admin/categories/course_select",:locals=>{:cur=>@course.category.get_tree} %></div>
        <%= f.label :price,"价格" %>  <br/>
        <%= f.text_field :price %> <br/>
        <%= f.label :age_range,"适合年龄" %>
        <% age_select=Course::AGE_RANGE %>
        <%= f.select :age_range, options_for_select(age_select.collect {|v| [v,age_select.index(v)]}) %>  <br/>
        <%=f.label :special, '特色'%>
        <%=f.text_field :special %>  <br/>
        <%=f.label :free_try, "试听" %>
        <%=f.select :free_try,[['无',false],['有',true]] %>  <br/>
        <%= f.label :website %><br/>
        <%= f.text_field :website %> <br/>
        <%= f.label :tags,'标签' %>   <br/>
        <%= f.text_field :tags %> <br/>
        <%= f.label :description,"课程描述" %> <br/>
        <%= f.kindeditor :description %> <br/>
        <% end %>
    <%= f.hidden_field :company_id,:value=>@course.company_id %>
    教育机构名称 <br>
    <%= text_field_tag "company",@course.company.name %>   <br>
<% end %>

app/views/companies/show.html+phone.erb
<%=content_tag :div, id: mobile_page_id, class: 'map_page',data:{role: 'page'} do %>
  <div data-role="header" data-position='fixed' >
  	<h1>优异思库</h1>
    <% if current_user.nil? %>
		  <%=link_to '登录',new_user_session_path,data: {role: "button",icon: 'user',iconpos: 'notext'}%>
		<% else %>
  	  <%=link_to "个人设置",'#',data: {role: 'button',icon: 'user',iconpos: 'notext'} %>
    <% end %>
  	<div>
      	<%=get_city_name %><%= link_to '<变更>',locations_path %>
  	</div>
  
    <div data-role="navbar">
      <ul >
        <li>
          <a href="/" class="parent"><span>首页</span></a>
        </li>
        <li>
          <a href="/lessons" class="parent"><span>课程</span></a>
        </li>
        <li>
          <a href="/companies" class="parent"><span>机构</span></a>
        </li>
        <li>
          <a href="/groups" class="parent"><span>社区</span></a>
        </li>
        <li>
          <a href="/places" class="parent"><span>携子同游</span></a>
        </li>
      </ul>
    </div>
	  <div class="segmented-control ui-bar-d">
  		<fieldset data-role='controlgroup' data-type='horizontal' data-mini='true'>
  			<input name='switch' id="list-switch" type='radio' checked='true'>
  			<label for= 'list-switch'>列表</label>
  			<input name='switch' id="map-switch" type='radio'>
  			<label for= 'map-switch'>地图</label>
  		</fieldset>
	  </div>
  </div>
  <%=content_tag :div,data: {role: 'content'} do %>
  	<div id="list-canvas" >
  	    <h2><%= @company.name %></h2> 
  	    <p>
    		  <b>网址:</b>
    		  <%=link_to @company.website,url_with_protocol(@company.website)%>
  		  </p>
  		  <p>
    		  <b>标签:</b>
    		  <%= @company.tags %>
  		  </p>
  		  <p>
    		  <b>公司简介:</b>
    		  <%= raw(@company.description) %>
  		  </p>
	
  	    <h3>各分支校区：</h3> 
  	    <%@company.branches.each do |branch| %>  
  		    <%=content_tag :div,class: 'branches', data: {positionx: branch.geolng, positiony: branch.geolat,title: branch.name} do %>
            <p><b>名称:</b><%=branch.name%></p>
            <p><b>电话:</b><%=branch.phone%></p>
            <p><b>地址:</b><%=branch.address %></p>
            <p><b>分支网址:</b><%=branch.website%></p>
  	        <%=content_tag :ul,id: "company_#{@company.id}_#{branch.id}",data: {role: 'listview',inset:'true'} do %>
  	          <% branch.lessons.each do |lesson|%>
	                  
    				    <li>  
      					  <%=link_to lesson.title, lesson_path(lesson) %> 
      	          <span class="ui-li-aside"><%=lesson.rank %>分</span>
      				  </li>
  			      <% end %>
  	        <% end %>
  		    <% end%>
  	   <% end %>
  	</div>
  	<div id='map-canvas' class='ui-content' role='main' style="display none;"></div>
    <%=render 'shares/footer'%>
	<% end%>
	
<% end %>

app/views/companies/show.html.erb
<div >
  机构详情&nbsp;<%=link_to '编辑', edit_company_path(@company) %> &nbsp; <%=link_to '历史',history_company_path(@company)%>
</div>
<div>
  <div>
  <p>
    <b>名称:</b>
    <%= @company.name %> &nbsp;  
    <%=link_to '添加课程',course_lessons_path(:company_id=>@company.id) %>
  </p>

<p>
  <b>网址:</b>
  <%= @company.website %>
</p>

<p>
  <b>标签:</b>
  <%= @company.tags %>
</p>

<p>
  <b>公司简介:</b>
  <%= raw(@company.description) %>
</p>
</div>

 
<div>
  <b>地点</b> <br/>

  <% n=rand(10000) %>
  <%@company.branches.each do |branch| %>

      <fieldset class='map_lists'>
        
          <div class='branch_message'>
            <p><b>名称</b><%=branch.name%></p>
            <p><b>电话</b><%=branch.phone%></p>
            <p><b>地址</b><%=branch.address %></p>
            <p><b>分支网址</b><%=branch.website%></p>
             <div>
                <% branch.lessons.each do |lesson|%>
                  <div>   课程名称：<%=lesson.title %> 
                          总分：<%=lesson.rank %> 
                          <%=link_to '详细',lesson_path(lesson)%>
                  </div>

                <% end %>
             </div>
          </div>
           <%= tag "div",{:id=>"mymap#{n}", :class=>"course_map small_map float_right",:data=>{:positionx=>branch.geolng,:positiony=>branch.geolat}},true  %>  <%=tag "/div","",true %>
        
         

        </fieldset>
      <% n+=1 %>
  <% end %>
  </div>




  <%= link_to '返回', companies_path %>
</div>