config/routes.rb
Uesku::Application.routes.draw do

 

  resources :places do 
    resources :comments ,:name_prefix=>"place_"
    resources :ratings, :name_prefix=>"place_"
  end

  resources :ratings 
  
  resources :pictures, :only=>[:index,:create,:destroy,:show]

  get "categories/index"
  get "categories/subcategory"

  

  get "profile/show"

  get "main/index"
  get "main/category/:id"  =>"main#category" ,:as=>:main_category
  get "main/location/:id"  =>"main#location", :as=>:main_location

  resources :locations,:only=>[:index] do 
    match 'select', :on=>:collection,:via=>[:get,:post]
    get 'set_city', :on=>:member
  end 

  resources :calendar_events

  resources :my_lessons

  resources :short_messages do
    get 'manage',:on=>:member
    get 'reply', :on=>:member
    post 'new_message',:on=>:collection
    get 'show_messages',:on=>:member
    post 'add_users',:on=>:collection
    post 'remove_users',:on=>:collection
    get 'new_messages',:on=>:member
  end

  resources :friendships  do
    get  'agree',:on=>:member
  end

 

  resources :posts  do
    get 'set_to_top',:on=>:member
    get 'set_to_distillate',:on=>:member
    get 'withdraw_to_top', :on=>:member
    get 'withdraw_distillate',:on=>:member
    resources :comments ,:name_prefix=>"post_"
  end

 resources :groups do
    resources  :posts,:name_prefix=>"group_"
    get "add_member",:on=>:member
    get 'administration',:on=>:member
    get 'approval_member',:on=>:member
    get 'reject_member',:on=>:member
    get 'set_manager',:on=>:member
    get 'withdraw_manager',:on=>:member
 end

  devise_for :admins, :controllers =>{:sessions=>'admin/sessions'}
  get 'admin/companies'=>'admin/companies#index',:as=>:admin_root

  devise_for :users, :controllers => { :omniauth_callbacks=>"users/omniauth_callbacks",:registrations=>"users/registrations" }
  
 

  resources :users,:only=>[:show,:edit] do
    get 'groups',:on=>:member
    get 'messenger',:on=>:member
    get 'profile',:on=>:member
    patch 'update_password',:on=>:collection
  end

  resources :companies ,:except=>[:destroy] do 
    get :select_company, :on=>:collection
    get 'history',:on=>:member
    post 'compare',:on=>:member
    get 'undo',:on=>:member
  end

  resources :lessons, :except=>[:destroy] do
    resources :comments,:name_prefix=>"lesson_"
    resources :scores
    resources :timetables,:name_prefix=>"lesson_"
    get 'undo',:on=>:member
    match 'category',:on=>:member,:via=>[:post,:get]
    match 'district',:on=>:member,:via=>[:post,:get]
    match 'course',:on=>:collection,:via=>[:post,:get]
    get 'history', :on=>:member
    post 'compare',:on=>:member
    get 'company',:on=>:collection
    
  end
  resources :timetables do
    get 'register_user',:on=>:member
    delete 'withdraw_user',:on=>:member
    get 'edit_calendar',:on=>:member
    post 'remove_class_time',:on=>:member
    post 'update_class_time', :on=>:member
    resources :comments,:name_prefix=>"timetable_"
  end

  resources :comments
  resources :replies

  post 'query/group_member_for_management'=>'query#group_member_for_management'
  get 'query/query_companies_auto'
  post 'query/query_companies'
  post 'query/query_users'

  namespace :api,defaults: {format: 'json'} do 
    namespace :v1 do 
      devise_for :users, :skip=>[:omniauth_callbacks]
      resources :calendar_events
      resources :users,:only=>[:show]
      resources :short_messages do
        get 'manage',:on=>:member
        get 'reply', :on=>:member
        post 'new_message',:on=>:collection
        get 'show_messages',:on=>:member
        post 'add_users',:on=>:collection
        post 'remove_users',:on=>:collection
        get 'new_messages',:on=>:member
      end
      resources :friendships  do
        get  'agree',:on=>:member
        post 'query_users',:on=>:collection
      end
    end
  end

  namespace :admin do
    resources :admins
    resources :branches,:except=>[:index,:show,:new]
    resources :lessons  do
      get 'set_audit',:on=>:member
      get 'withdraw_audit',:on=>:member
      get 'list',:on=>:collection
      resources :recommendations
    end
    resources :categories   do
      post 'select', :on=>:collection
      post 'course_select',:on=>:collection
    end
    resources :locations   do
      post 'select', :on=>:collection
      
    end

    resources :companies do
    resources :branches
     get  'set_audit', :on=>:member
     get  'withdraw_audit', :on=>:member
    resources :courses    do
      get  'set_audit', :on=>:member
      get  'withdraw_audit', :on=>:member
    end
    end

  end

  authenticated :user do
    root :to=>'users#show',:as=>:root_user
  end
  authenticated :admin do 
    root :to=>'admin/lessons#index',:as=>:root_admin
  end
  root :to => 'main#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  #attr_accessible :city_id, :description, :direction, :district_id, :opening_hours, :phone, :latitude, 
  #				  :longitude, :price, :province_id, :street, :title, :website,:pictures,:tag_list,:user_id
  belongs_to :province,:class_name=>'Location',:foreign_key=>'province_id'
  belongs_to :city, :class_name=>'Location',:foreign_key=>'city_id'
  belongs_to :district,:class_name=>'Location',:foreign_key=>'district_id'
  belongs_to :user
  has_many :pictures,:as=>:has_picture
  has_many :comments, :as =>:commentable
  has_many :ratings, :as=>:ratingable
  validates_presence_of :title,:street
  has_paper_trail
  acts_as_taggable

  def pictures=(args)
    args.each do |arg|
      picture=Picture.find(arg)
      self.pictures<<picture
    end
  end


   def address
        if province.name == city.name
          city.name+district.name+street
        else
          province.name+city.name+district.name+street
        end
    end

    def recount_rank
      self.rank=ratings.average('value')
      self.rank_count=ratings.count
      save!
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
   layout :set_layout
  respond_to :html
  before_filter :authenticate_user!, :except=>[:index,:show]
  
  def index
    if params[:tag]
      @places=Place.tagged_with(params[:tag]).paginate(:page=>params[:page],per_page: 20)
    else
      @places = Place.paginate(:page=>params[:page],per_page: 20)
    end

    respond_with  @places do |format|
      format.html
      format.js
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    @rating=@place.ratings.where(:user_id=>current_user.id).first

    respond_with [@place,@rating]
      
    
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new
   

   respond_with @place
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.user_id=current_user.id
     @place.save
    respond_with @place
     
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])
    @place.update_attributes(place_params)
    respond_with @place
      
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    respond_with @place
  end
  
  private
  def place_params
    params.required(:place).permit(:city_id, :description, :direction, :district_id, :opening_hours, :phone, :latitude,:longitude, :price, :province_id, :street, :title, :website,:pictures,:tag_list,:user_id)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= nested_form_for @place,:multipart=>true do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class='has_map'>
  <div class="field">
    <%= f.label :title,'名称：' %>
    <%= f.text_field :title %>
  </div>
 
  <div class="field">
    标签：<%=f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :phone,"电话" %>
    <%= f.text_field :phone %>
  </div>
   <div class="field">
    <%= f.label :price,"价格" %>
    <%= f.text_field :price %>
  </div>
   <div class="field">
    <%= f.label :opening_hours,"开放时间" %>
    <%= f.text_field :opening_hours %>
  </div>
  <div class="field">
    <%= f.label :description,"介绍及推荐理由" %><br />
    <%= f.kindeditor :description %>
  </div>
  <div class='address'>
          地址：<%=f.select :province_id,options_for_select(Location.roots.order(:id).collect {|p| [p.name,p.id]}),{},:class=>'province' %> 
          <%=f.select :city_id,options_for_select(Location.first_cities.collect{|p| [p.name,p.id]}),{},:class=>'city'  %> 
          <%=f.collection_select :district_id,Location.first_districts,:id,:name,{},:class=>'district' %> 
          <%=f.text_field :street,:class=>'street' %><div class='map_notice'></div>
  </div>
 
 
 
  <div class="field">
   
    <%= f.hidden_field :latitude,:class=>'positiony' %>
    <%= f.hidden_field :longitude,:class=>'positionx' %>
  </div>
  <div >

        <div><b>点击地图设定分支所在位置：</b></div>
        <%=tag "div",{:class=>"mymap set_point",:id=>"mymap#{rand(1000)}"},true%>
        <%=tag "/div",nil,true%>
  </div>

  <div class="field">
    <%= f.label :direction,'交通指引' %><br />
    <%= f.text_area :direction,:cols=>80,:rows=>5 %>
  </div>
  
     
  <div id="pictures">
  
  </div>
  
  <div class="actions">
    <%= f.submit "提交" %>
  </div>
</div>
<% end %>

<fieldset>
  <h3>图片管理</h3>
<%= form_for Picture.new, :html => { :multipart => true, :id => "fileupload" ,:data=>{:place=>@place.id,:name=>@place.class.name} } do |f| %>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>增加图片...</span>
                    <%= f.file_field :image %>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>开始上传</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>中断上传</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span>删除</span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
    <% end %>
  </fieldset>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>上传</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>取消</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>删除</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>

app/views/places/_list_items.html.erb
<% @places.each do |place| %>
  <li>
    <%=link_to place_path(place) do %>
      <h3><%=place.title%></h3>
      <p>
        <%=place.address%><br/>
        标签：<%=place.tag_list%>
      </p>
      <span class="ui-li-aside">推荐指数：<%=place.rank%></span>
    <% end %>
  </li>
<% end %>

app/views/places/edit.html.erb
<h1>修改地点</h1>

<%= render 'form' %>

<%= link_to '显示', @place %> |
<%= link_to '返回', places_path %>

app/views/places/index.html+phone.erb
<%=content_tag :div,id: mobile_page_id,data: {role: 'page'} do %>
  <%=render 'shares/header'%>
  <%=content_tag :div, data: {role: 'content'} do %>
    <ul data-role='listview' class='lists_phone'>
       <%=render 'list_items'%>      
    </ul>
    <div id="paginate_area"> 
      <%=will_paginate @places,:previous_label=>'前页',:next_label=>'下页'%>
    </div>
  
  <%=render 'shares/footer'%>
  <% end %>
<% end %>

app/views/places/index.html.erb
<div class="list">
  <% @places.each do |place| %>
  <ul class='list_item'>
    <li class='float_left cell_detail'>
      <ul>
        <li><strong><%= link_to place.title,place_path(place) %></strong></li>
        <li>地址:<%=place.address %></li>
        <li>电话:<%=place.phone %></li>
        <li>标签:<%=place.tag_list %></li>
        <li>开放时间:<%=place.opening_hours %></li>
      </ul>
    </li>
    <li class='float_left cell_price'>
      <%=place.price %>
    </li>
    <li class='float_left cell_rank'>
      <ul>
        <li>推荐指数：<%=place.rank %></li>
        <li>共有<%=place.rank_count %>人推荐</li>
      </ul>
    </li>
    <div class='noad'></div>
   </ul>
  <% end %>
 </div>






<%= link_to '新建地点', new_place_path %>

app/views/places/index.js.erb
$("ul[data-role='listview'].lists_phone").append('<%=j render 'list_items' %>').listview('refresh');
<% if @places.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @places %>');
<% else %>
	$(document).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/places/new.html.erb
<h1>新建地点</h1>

<%= render 'form' %>

<%= link_to '返回', places_path %>

app/views/places/show.html+phone.erb
<%=content_tag :div, id: mobile_page_id,data: {role: 'page'} do %>
  <%=render 'shares/header'%>
  <%=content_tag :div, data:{role: 'content'} do %>
    <h2> <%= @place.title %></h2>
    <div class='details'>  
      <div>
        推荐指数：<%=@place.rank %>,共有<%=@place.rank_count %>人推荐
      </div>
      <div>
        标签：<%=raw @place.tag_list.map {|tag| link_to tag, places_path(:tag=>tag)}.join(',') %>
      </div>
      <div>
        地址：<%=@place.address %>
      </div>
      <div>
       电话： <%=@place.phone %>
      </div>
      <div>
        Website: <%= link_to @place.website,url_with_protocol(@place.website),:target=>'_blank' %> 
      </div>
      <div>
        价格：<%= @place.price %>
      </div>
      <div>
       开放时间:<%=@place.opening_hours %>
      </div>
    </div>
    <div >简介及推荐理由</div>
    <div class='details' >
      <%=raw @place.description %>
    </div>
    <div >位置交通</div>
    <div class='details'>
      <%=content_tag 'div', :id=>'lesson_map',:data=>{:positiony=>@place.latitude,:positionx=>@place.longitude} do %>
      <% end %>
      <div >
        <%=@place.direction %>
      </div>
    </div>
    <div id='phoneScrollable'>
      <% @place.pictures.each do |p| %>
        <%=image_tag p.image_url.to_s,height: 150 %>
      <% end %>
    </div>
    <div>评价：</div>
    <%=content_tag :div, id: 'comment_list',class: 'details', data: {id: @place.id,type: @place.class.name.downcase.pluralize} do %>
    <%end%>
    <%=render 'shares/footer'%>
    <div id='myrating' data-role='popup'>
      <div>
        <b>推荐指数：</b>
        <%=content_tag 'div',:id=>"start_rating", :data=>{:url=>place_ratings_path(@place),:id=>@rating.try(:id)} do %>
          <% (1..5).each do |v| %>
            <%= radio_button_tag 'rank',v,@rating.try(:value)==v, :class=>'auto-submit-star' %> 
          <% end %>
        <% end %>
        <div>
           1星为千万不要去，5星为非常值得去，请做出您的推荐
        </div>
    </div>
  
    
  
  <% end %>
  <%=content_tag :div, data:{role:'footer',position:'fixed'} do %>
    <div data-role='navbar'>
      <ul>
        <li>
          <a href='#myrating' data-rel='popup'> 评分</a>
        </li>
        <li>
          <%=link_to '评论',new_comment_path(:place_id=>@place)%>
        </li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :author do %>
  <div id="user_bar" >
    <h1>作者 </h1>
    <div><%=image_tag @place.user.avatar_url.to_s,:width=>150,:height=>150 %>  </div>
    <div>
      <%=link_to @place.user.name,profile_user_path(@place.user) %>
    </div>
    <div>
      <div>注册时间:<%=format_time(@place.user.registration_date) %></div>
      <div>积分:<%=@place.user.score %></div>
    </div>
  </div>
<% end %>
<div class='toolbar'><%= link_to '修改', edit_place_path(@place) if @place.user==current_user%></div>
<div id='lesson_title'> <%= @place.title %></div>
<div class='details'>
  
  <div class='float_right'>
    推荐指数：<%=@place.rank %>,共有<%=@place.rank_count %>人推荐
  </div>
  <div>
    标签：<%=raw @place.tag_list.map {|tag| link_to tag, places_path(:tag=>tag)}.join(',') %>
  </div>
  <div>
    地址：<%=@place.address %>
  </div>
  <div>
   电话： <%=@place.phone %>
  </div>
  <div>
    Website: <%= link_to @place.website,url_with_protocol(@place.website),:target=>'_blank' %> 
  </div>
  <div>
    价格：<%= @place.price %>
  </div>
  <div>
   开放时间:<%=@place.opening_hours %>
  </div>
</div>
<div class='detail_bar'>
  <div class='detail_head'>简介及推荐理由</div>
</div>
<div class='details' >
  <%=raw @place.description %>
</div>

<div class='detail_bar'><div class='detail_head'>位置交通</div></div>
<div class='details'>
  <%=content_tag 'div', :id=>'lesson_map',:class=>"float_right",:data=>{:positiony=>@place.latitude,:positionx=>@place.longitude} do %>
  <% end %>
  <div class='direction'>
    <%=@place.direction %>
  </div>
</div>
<div class='details'>
<div id='makeMeScrollable'>
  <% @place.pictures.each do |p| %>
    <%=image_tag p.image_url.to_s %>
  <% end %>
</div>
</div>
<div class='detail_bar'><div class='detail_head'>大众评价</div></div>
<%=content_tag :div, id: 'comment_list',class: 'details', data: {id: @place.id,type: @place.class.name.downcase.pluralize} do %><%end%>
<% unless current_user.nil? %>
  <div class="details">
    <div>
      <b>推荐指数：</b>
      <%=content_tag 'div',:id=>"start_rating", :data=>{:url=>place_ratings_path(@place),:id=>@rating.try(:id)} do %>
        <% (1..5).each do |v| %>
          <%= radio_button_tag 'rank',v,@rating.try(:value)==v, :class=>'auto-submit-star' %> 
        <% end %>
      <% end %>
      <div>
         1星为千万不要去，5星为非常值得去，请做出您的推荐
      </div>
    </div>
   <div id='comment_area' class='float_right'>

         <%=form_for [@place,Comment.new],:remote=>true do |f|%>
           
            <%=f.text_area :comment,:cols=>60,:rows=>8,:id=>'input_comment_area'%>
            <div id="errmsgs"></div>
             <%=f.submit '发布'%>
         <% end %>
    </div>

  </div>
<% end %>
 